id: A5EE70099
title: 'The Chariot of the Vidyādharas: An Aspiration Prayer for Travelling to the
  Realm of Lotus Light'
type: translation
pechas:
- I1E1A4797
- IE8F89D00
- I84867F87
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:31:59.270990
  last_modified_at: 2023-01-04 12:31:59.271009
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I1E1A4797/2DDF: '0015'
  IE8F89D00/2D3F: '0015'
  I84867F87/0331: '0015'
